#!/usr/bin/env bash
#
# Pre-commit hook: validate ocpn-plugins.xml and check whitespace errors.
#   - Requires xmllint and python available on $PATH.
#   - Copy to .git/hooks to activate.
#   - Use --no-verify to override.

topdir=$(git rev-parse --show-toplevel)

for f in $(git diff --cached --name-only --diff-filter=ACM); do
    if [[ $f != *.xml ]]; then continue; fi
    xmllint --schema $topdir/ocpn-plugin.xsd  $f --noout || exit 1
    python $topdir/tools/check-metadata-urls $f || exit 1
done

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached HEAD --
