#!/usr/bin/env bash
#
# Pre-commit hook: validate ocpn-plugins.xml and check whitespace errors
#   - Requires xmlllint available on $PATH.
#   - Copy to .git/hooks to activate.
#   - Use --no-verify to override.

set -euo pipefail

function files_to_update()
{
    git diff --cached --name-status | grep -v ^D | awk '{print $NF}'
}
topdir=$( git rev-parse --show-toplevel )
here=$(dirname $0)

XML_SOURCES=( $( files_to_update | grep -E '\.xml$'))

if [ -n "$XML_SOURCES" ]; then
  for f in "${XML_SOURCES[@]}"
  do
    xmllint --schema "${topdir}/ocpn-plugin.xsd" "${f}" --noout || exit 1
    python "${here}/../../tools/check-metadata-urls" "${f}" || exit 1
  done
fi

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached HEAD --
