#!/usr/bin/env bash
#
# Pre-commit hook: validate ocpn-plugins.xml and check whitespace errors
#   - Requires xmlllint available on $PATH.
#   - Copy to .git/hooks to activate.
#   - Use --no-verify to override.

function files_to_update()
{
    git diff --cached --name-status | grep -v ^D | awk '$1 $2 { print $2}'
}

topdir=$( git rev-parse --show-toplevel )

XML_SOURCES=( $( files_to_update | grep -E '\.xml$'))

if [ -n "$XML_SOURCES" ]; then
  xmllint --schema $topdir/ocpn-plugins.xsd  $XML_SOURCES --noout || exit 1
fi

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached HEAD --
