#!/bin/bash

branch=$CIRCLE_BRANCH

sudo apt update
sudo apt install -y libxml2-utils python3
sudo update-alternatives --install /usr/bin/python python /usr/bin/python3.*  2

git remote add upstream https://github.com/OpenCPN/plugins.git
if ! git ls-remote --exit-code --heads upstream $branch; then
    echo "Branch $branch can not be found on upstream, no checks done"
    exit 0;
fi
git fetch upstream $branch

topdir=$(git rev-parse --show-toplevel)
for f in $(git diff --name-only --diff-filter=ACMR upstream/$branch HEAD); do
    if [[ $f != *.xml ]]; then continue; fi
    xmllint --schema $topdir/ocpn-plugin.xsd  $f --noout || exit 1
    python $topdir/tools/check-metadata-urls $f || exit 1
done
